# Generated by Django 5.1 on 2024-09-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0002_account_plaid_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='plaid_account_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
