# Generated by Django 5.1 on 2024-09-14 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0003_alter_account_plaid_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='plaid_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
